-- MySQL Script generated by MySQL Workbench
-- 09/13/16 17:31:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbcursosvirtual
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbcursosvirtual
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbcursosvirtual` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema dbmatricula
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbmatricula
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbmatricula` DEFAULT CHARACTER SET latin1 ;
USE `dbcursosvirtual` ;

-- -----------------------------------------------------
-- Table `dbcursosvirtual`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcursosvirtual`.`categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nombre` VARCHAR(30) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idCategoria`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbcursosvirtual`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcursosvirtual`.`curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `idCategoria` INT NOT NULL COMMENT '',
  `Monto` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idCurso`)  COMMENT '',
  INDEX `idCategoria_idx` (`idCategoria` ASC)  COMMENT '',
  CONSTRAINT `idCategoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `dbcursosvirtual`.`categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbcursosvirtual`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcursosvirtual`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nombre` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `DNI` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `Correo` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `Usuario` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `Clave` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `Rol` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idUsuario`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbcursosvirtual`.`inscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcursosvirtual`.`inscripcion` (
  `idInscripcion` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Fecha_inscripcion` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `idUsuario` INT NULL COMMENT '',
  `idCurso` INT NULL COMMENT '',
  PRIMARY KEY (`idInscripcion`)  COMMENT '',
  INDEX `idUsuario_idx` (`idUsuario` ASC)  COMMENT '',
  INDEX `idCurso_idx` (`idCurso` ASC)  COMMENT '',
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `dbcursosvirtual`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCurso`
    FOREIGN KEY (`idCurso`)
    REFERENCES `dbcursosvirtual`.`curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbcursosvirtual`.`temario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcursosvirtual`.`temario` (
  `idTemario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nombre_temario` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `Duracion` VARCHAR(30) NULL DEFAULT NULL COMMENT '',
  `idCurso` INT NULL COMMENT '',
  PRIMARY KEY (`idTemario`)  COMMENT '',
  INDEX `idCurso_idx` (`idCurso` ASC)  COMMENT '',
  CONSTRAINT `idCurso`
    FOREIGN KEY (`idCurso`)
    REFERENCES `dbcursosvirtual`.`curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


